### ISSUE TITLE
Trello updated their labels

### ISSUE THREAD

**Issue by spencerstark** [jeremytregunna/ruby-trello#105]
new labels: pink sky lime black

Label_name.rb needs to be updated to accommodate as well as card.rb

**Comment by wireframe** [comment]
It would be great to support arbitrary label names offered by the API.  currently, card creation [only support a subset of the available colors](https://github.com/jeremytregunna/ruby-trello/blob/7626965931c67eec0c0230bfa87929f596bd95a1/lib/trello/card.rb#L216)
