### ISSUE TITLE
I get undefined method `config' for Trello:Module on config

### ISSUE THREAD

**Issue by kevinchugh** [jeremytregunna/ruby-trello#131]
Have you ever seen this? I literally copy and paste your example and I get this.  Here's my code:

Trello.configure do |config|
        config.developer_public_key = TRELLO_API_KEY
        config.member_token = TRELLO_TOKEN
 end

**Comment by Anti-Fun** [comment]
Replace the TRELLO_API_KEY and TRELLO_TOKEN with your API key. Or a better practise, is to store them in environment variables on the server.

**Comment by kevinchugh** [comment]
This was an rvm issue, we can close this, thanks for your response.

**Comment by ryanfelton** [comment]
I get this same message when including the `pivotal-tracker` gem. It seems to me the Trello configuration isn't namespace properly.
