### ISSUE TITLE
Taking a step back.

### ISSUE THREAD

**Issue by jeremytregunna** [jeremytregunna/ruby-trello#141]
For a while now I've not been able to give this gem the attention it deserves. It was originally created for a tool that no longer lives, and I'm certainly not in the best position to drive the direction of the gem going forward. For those reasons, let me apologize to those of you who use this gem and have been frustrated with its maintenance.

So I'd like to talk about the direction of this gem. I'd rather not just stop releasing updates, there are folks using this in their apps today, which is great. But I also don't have the time to keep it in good condition.

**Comment by christoshrousis** [comment]
Is it a matter of someone taking over, or is there a way to give access to multiple people so that it doesn't rely solely on yourself?

**Comment by MrPowers** [comment]
The pull request hack might help: http://felixge.de/2013/03/11/the-pull-request-hack.html

This is a pretty popular gem and I think it will be easy for you to find contributors that can merge pull requests and add features :smile: 

I use this gem in a bunch of apps and it works great.  I think the open source community can keep it awesome.

**Comment by jeremytregunna** [comment]
@christoshrousis I'd prefer the latter than the former naturally.

**Comment by jeremytregunna** [comment]
@MrPowers that's a really clever idea, and I think I like it.

**Comment by christoshrousis** [comment]
Well yeh, I believe it's called being the Benevolent Dictator. Where a handful of people argue it over, and you're the last point of call for decision making. But ultimately you don't need to do anything because it never gets that far, and the major committers work it out among themselves.

**Comment by MrPowers** [comment]
@jeremytregunna - Did you come up with a conclusion / path forward?

**Comment by jeremytregunna** [comment]
Yes. From now on whenever a new pull is accepted and merged, I'll add that person as a contributor to the repo.
