### ISSUE TITLE
Add extra attributes to Board and Attachment

### ISSUE THREAD

**Issue by gorenje** [jeremytregunna/ruby-trello#148]
Hi, 

I've added [last_activity_date](https://github.com/gorenje/ruby-trello/commit/57ec977aad03e6c7182fb123f2de020eb41b47d5) to Board and [previews](https://github.com/gorenje/ruby-trello/commit/ebe507fe482c90630f1bf113bd87402075a877e4) to Attachment, is there a realistic chance that this could be added to the gem?

Both are needed for our usecase of filling a Algolia search engine.

Cheers!

**Comment by jeremytregunna** [comment]
@gorenje Absolutely, make a pull request!

**Comment by jeremytregunna** [comment]
Closing this, as it's been answered, but looking forward to the pull request with your changes as a separate issue.
