### ISSUE TITLE
New gem version with CVE fix?

### ISSUE THREAD

**Issue by iancanderson** [jeremytregunna/ruby-trello#151]
Hi, I was hoping you could bump the version of the gem and push to rubygems so we could use an officially release version of the gem that has the rest-client CVE fix (see https://github.com/jeremytregunna/ruby-trello/pull/133).

Let me know if a PR would help to bump the actual version number in the repo.

**Comment by hrogers-ezcater** [comment]
LGTM. Like the PR! jeremytregunna/ruby-trello/issues/151

**Comment by joneslee85** [comment]
cc @jeremytregunna

**Comment by jeremytregunna** [comment]
@iancanderson Thank you for this poke, I'll get one out tonight.

**Comment by jeremytregunna** [comment]
1.3.0 has been pushed out, tagged and master updated.

**Comment by iancanderson** [comment]
thanks!
