### ISSUE TITLE
Unable to update field(s) for card

### ISSUE THREAD

**Issue by nielsvs** [jeremytregunna/ruby-trello#152]
There seem to be some bugs in this library. the necessary parameters are not available on line 204 of client.rb, so it can't update, and it's actually trying to POST a new card because update! isn't being called.

Test case: 
Trello::Card.find(trello_id).update_fields(:name => "test name updated").save

It returns an "invalid value for idList" error. I can find the card with the corresponding 'trello_id' and all it's attributes just fine.

**Comment by joneslee85** [comment]
@nielsvs would you be able to submit a PR having this failed spec?

**Comment by nielsvs** [comment]
@joneslee85  PR as in private repository or PR as in pull request?

**Comment by joneslee85** [comment]
@nielsvs Pull Requests please

**Comment by jeremytregunna** [comment]
@nielsvs Is this still a problem for you using the master branch? Please advise. If not, I'll push out a release.

**Comment by nielsvs** [comment]
@jeremytregunna yes, it's still a problem for me using the master branch.

**Comment by joneslee85** [comment]
@nielsvs it seems to be very out of date this issue, can you please advise if it is resolved or not? if not, would you be able to submit a patch?

**Comment by joneslee85** [comment]
There has not been any update since. I am closing this ticket. Please feel free to re-open.

**Comment by artempokutnii** [comment]
Hi guys, this problem is still actual.

**Comment by DanteAlg** [comment]
I had the same problem when try to create a new card. Solved using list_id instead idList.
`
Trello::Card.create(list_id: 'trello_id', name: 'Teste api', desc: 'Lorem ipsum dollor')
`

**Comment by flyingolivier** [comment]
I believe that doing this
```
card = Trello::Card.find(trello_id).name = "test name updated"
card.save
```

instead of this
```
Trello::Card.find(trello_id).update_fields(:name => "test name updated").save
```

should work

Not very familiar with the gem code, but it looks like that `update_fields(fields)` sets to `nil` any attribute not defined in the received parameters. Here the `list_id` attribute becomes `nil` making the object invalid.
