### ISSUE TITLE
Trello is making a small modification to the checklist API

### ISSUE THREAD

**Issue by PeEllAvaj** [jeremytregunna/ruby-trello#159]
Trello has an upcoming breaking change to the API that will mean that all checklists MUST have a idCard at creation, and this idCard cannot be changed later (no moving of Checklists). This change is to prevent the creation of orphaned checklists, which has started to become a problem for several use cases.

I'd love to work with you to get this resolved ASAP in the library before this change goes into production later this month.

**Comment by joneslee85** [comment]
@PeEllAvaj please give it a go, if you need any help, just reply to this issue

**Comment by joneslee85** [comment]
ping

**Comment by PeEllAvaj** [comment]
https://github.com/jeremytregunna/ruby-trello/pull/161 makes it so that you can create a checklist with a cardID (which you must do).  The only thing left would be to remove the boardId from the `post` and the `create` method

**Comment by qpowell** [comment]
@PeEllAvaj any word on this? Currently unable to create checklists due to the idCard value not being passed.

**Comment by jeremytregunna** [comment]
@PeEllAvaj Is anything left to be done on this? It's the only thing holding back a new release that should be go out soon.

**Comment by PeEllAvaj** [comment]
@jeremytregunna I'm not 100% sure because I don't have a code sample to test the library with, but reviewing the changes to the checklist.rb file makes it look like that should work. We formally deprecated this route about a month ago, so if it's working today, it's going to keep working.
