### ISSUE TITLE
All calls on member result in: 'can't convert Trello::AssociationProxy to Array (Trello::AssociationProxy#to_ary gives Trello::MultiAssociation)'

### ISSUE THREAD

**Issue by krazerxz** [jeremytregunna/ruby-trello#160]
Having trouble getting any methods on a member to return anything using basic auth. 

``` ruby
Trello.configure do |config|
   config.developer_public_key = 'something'
   config.member_token = 'something_else'
end
member = Trello::Member.find('my_username')
```

calling member.cards, member.boards or member.organizations all give the error:

``` ruby
can't convert Trello::AssociationProxy to Array (Trello::AssociationProxy#to_ary gives Trello::MultiAssociation)
```

Feels like I'm just doing something very stupid.
Thanks for any help.

**Comment by hakunin** [comment]
Not sure whats the problem there, but I am having success with:

```
    client ||= Trello::Client.new(
      consumer_key: ENV['TRELLO_KEY'],
      consumer_secret: ENV['TRELLO_SECRET'],
      oauth_token: options[:token],
      oauth_token_secret: options[:secret],
    )

    @me = client.find(:members, 'me')
    @boards = @me.boards
```

and then I access cards via boards

**Comment by joneslee85** [comment]
@krazerxz i am going to close this ticket because it has been too long without reply. Feel free to re-open it if it you have not yet resolved it
