### ISSUE TITLE
Thread safe features documentation

### ISSUE THREAD

**Issue by hakunin** [jeremytregunna/ruby-trello#168]
Hi,
I want to create a Trello import and for that I need to list user's boards and their cards.

But, how do I event list the boards? Readme doesn't say and there seems to be zero documentation on how to use `find_many`, which seems to be only suitable for internal use by the gem itself.

**Comment by joneslee85** [comment]
The README is not meant to be the source of all API references.

API in fact is documented in https://github.com/jeremytregunna/ruby-trello/blob/46f243acedb227ce5c398cf8d1427a2aa8cf8075/doc/table_of_contents.html#L361

Please consult `doc/` folder. If it is not there, I tend to look for the spec of the class. If the spec does not cover the method, you can make a PR and improve the doc and test coverage.

**Comment by hakunin** [comment]
I've been through the gem's code and the documentation too and its not documented as far as I can tell.

The method you referenced isn't documented (doesn't have an example, doesn't explain what it does)
http://www.rubydoc.info/gems/ruby-trello/Trello/Client#find_many-instance_method

The best way to work with this gem thread-safely is to use this:

```
client = Trello::Client.new(
      consumer_key: ENV['TRELLO_KEY'],
      consumer_secret: ENV['TRELLO_SECRET'],
      oauth_token: user_token, 
      oauth_token_secret: user_secret,
    )

# first we start by establishing the user's object
me = Trello::Member.parse(client.get("/members/me/"))

# set the client, which carries the thread-safe credentials
me.client = client

# the client is passed from that point onwards
me.organizations
me.organizations.map(&:boards)
```

**Comment by rossta** [comment]
@hakunin When working with separate `client` objects, you just need to pass the resource name as the first argument in your initial request, e.g. `client.find(:members, 'me')`. The client that makes the initial request will be assigned as the internal client of return object(s). I think you can eliminate a few steps in your example.

Compare:

```ruby
member = Trello::Member.find('rossta')    # use global client instance implicitly
member.organizations                              # use global client instance implicitly
```

with

```ruby
client = Trello::Client.new(credentials)      # initialize local client instance
member = client.find(:members, 'rossta')  # use local client instance explicitly
member.organizations                               # use local client instance implicitly
```

In most cases, I don't believe you'd need set the client yourself on Trello instances. Does that help?

**Comment by hakunin** [comment]
Thanks!

On Tue, Dec 8, 2015 at 8:22 PM Ross Kaffenberger <notifications@github.com>
wrote:

> @hakunin <https://github.com/hakunin> When working with separate client
> objects, you just need to pass the resource name as the first argument in
> your initial request, e.g. client.find(:members, 'me'). The client that
> makes the initial request will be assigned as the internal client of return
> object(s). I think you can eliminate a few steps in your example.
>
> Compare:
>
> member = Trello::Member.find('rossta')    # use global client instance implicitly
> member.organizations                              # use global client instance implicitly
>
> with
>
> client = Trello::Client.new(credentials)      # initialize local client instance
> member = client.find(:members, 'rossta')  # use local client instance explicitly
> member.organizations                               # use local client instance implicitly
>
> In most cases, I don't believe you'd need set the client yourself on
> Trello instances. Does that help?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jeremytregunna/ruby-trello/issues/168#issuecomment-162987958>
> .
>
-- 
S pozdravem, Regards
Michal Hantl

skype id: michal.hantl
cell phone: +420 720 737 902
