### ISSUE TITLE
Adding Due Date

### ISSUE THREAD

**Issue by wayferer** [jeremytregunna/ruby-trello#177]
Just in case it helps others. I was unable to add a due date to a card when creating. This is what I used to be able to add a due date:

````
card = Trello::Card.create(name: 'Name', desc: "A description", list_id: 'abcd123456')

card.due = DateTime.now
card.save
````

**Comment by jeremylinlin** [comment]
Thanks, it helps!

**Comment by mjankowski** [comment]
This was useful in tracking this down - https://github.com/jeremytregunna/ruby-trello/issues/238

Summary: use iso8601 format when supplying a `due` value.
