### ISSUE TITLE
Empty response body on non-success response

### ISSUE THREAD

**Issue by kexline4710** [jeremytregunna/ruby-trello#185]
I've got a cronjob using the ruby-trello gem to pull GitHub issues and create Trello cards, but I frequently encounter a `Trello::Error` with no error message when attempting to fetch a list. I can see [here][body] that the library uses the response body for the error message, but do you know of any cases where a response would return a blank response body from Trello? There was no information in the documentation for this gem or in the Trello docs.

I have not been able to recreate a blank response body when pinging the Trello api directly, so I thought I would check here first. Let me know if there is a better place/person to ask. Thanks!

[body]: https://github.com/jeremytregunna/ruby-trello/blob/master/lib/trello/client.rb#L97-L100

**Comment by rossta** [comment]
@kexline4710 I haven't seen that myself. Can you get a stacktrace? Do you see any output from the previous line to the `Trello.logger` in your logs?

**Comment by kexline4710** [comment]
Yeah, here is the stacktrace that I'm looking at:
```
E, [2016-01-13T15:37:23.558885 #26009] ERROR -- : [ GET https://api.trello.com/1/boards/<our_board_id>/lists?filter=open]:
Trello::Error
/var/lib/gems/1.9.1/gems/ruby-trello-1.2.1/lib/trello/client.rb:99:in `invoke_verb'
/var/lib/gems/1.9.1/gems/ruby-trello-1.2.1/lib/trello/client.rb:19:in `get'
/var/lib/gems/1.9.1/gems/ruby-trello-1.2.1/lib/trello/client.rb:53:in `find_many'
/var/lib/gems/1.9.1/gems/ruby-trello-1.2.1/lib/trello/basic_data.rb:95:in `block (2 levels) in many'
```

**Comment by codyolsen** [comment]
@kexline4710 I have a couple questions:

1. How often is the script running?
2. Are you running multiple threads or calling the API at the same time using another script or process?

Your stacktrace helps but, as @rossta mentioned, there is a [`Trello.logger` call](https://github.com/jeremytregunna/ruby-trello/blob/master/lib/trello/client.rb#L98) right before the exception raise in the `invoke_verb` method. Knowing the contents of the logger at the time of your error would help to narrow the cause to either Trello's api or the ruby-trello gem.

**Comment by Flip437** [comment]
Hi,

Can someone tell me how to deals with Trello::Error ?
I'd love to get the error code to do some request tests but when I try to create a card with bad request, I have
Trello::Error: invalid value for idList.

I do on purpose Trello::Card.create(name: "GOOD_NAME", list_id: "List ID that doesn't exists")
So I expect the response to have 400 status, so the test succed.
But now, the test crashes and the test doen't not pass, I just those red letters that tell "invalid value for idList ...
How should I do to save Trello::create response and test this response.


Thanks a lot !!

**Comment by hoppergee** [comment]
Hi @Flip437 

You can get the response status and message through `rescue`:

```ruby
begin
  Trello::Card.create(name: "GOOD_NAME, list_id" "List ID that doesn't exists")
rescue => error
  error.status_code #=> 400
  error.message #=> "invalid value for idList"
end
```

This may not be the way you're used to. But it is by design. I may try to change it to an intuitive way in future. For now, you have to do it with `rescue`.

References:

https://github.com/jeremytregunna/ruby-trello/blob/335f6aab7c9cf60f4ff6f70c894ba2aae87ec9fa/lib/trello/client.rb#L92-L100

https://github.com/jeremytregunna/ruby-trello/blob/335f6aab7c9cf60f4ff6f70c894ba2aae87ec9fa/lib/trello/error.rb#L1-L12

**Comment by Flip437** [comment]
Hi @hoppergee 

thank you for the answer!
Yes, I've found the way to do in another API Gem doc that works pretty much the same ^^
Thanks a lot :)

flip.
