### ISSUE TITLE
Dependency resolution failure on Rails 5 beta 4

### ISSUE THREAD

**Issue by ksamc** [jeremytregunna/ruby-trello#188]
When trying to install the gem on a new Rails 5 beta 4 app I get the following dependency resolution failure message from Bundler:

````
Bundler could not find compatible versions for gem "mime-types":
  In snapshot (Gemfile.lock):
    mime-types (= 3.0)

  In Gemfile:
    rails (< 5.1, >= 5.0.0.beta4) was resolved to 5.0.0.beta4, which depends on
      actionmailer (= 5.0.0.beta4) was resolved to 5.0.0.beta4, which depends on
        mail (>= 2.5.4, ~> 2.5) was resolved to 2.6.4, which depends on
          mime-types (< 4, >= 1.16)

    ruby-trello was resolved to 1.4.1, which depends on
      rest-client (~> 1.8.0) was resolved to 1.8.0, which depends on
        mime-types (< 3.0, >= 1.16)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
````

The dependency has been fixed in master: https://github.com/rest-client/rest-client/commit/d401bba5285fe426568414b1ca0d16d22c17a975

I guess we have to wait for a release there first. In the meantime I'll just use mime-types v2.99.1.

**Comment by jeremytregunna** [comment]
Just pushed 1.4.2 up which should resolve this problem. Closing, but will reopen if you're still seeing the problem.

**Comment by ksamc** [comment]
@jeremytregunna thanks!
