### ISSUE TITLE
Should calling Save on a Trello Client also run create?

### ISSUE THREAD

**Issue by Haziba** [jeremytregunna/ruby-trello#192]
Trying to create a new webhook using a client with this line:

`trello.create(:webhook, callback_url: my_hook.url, id_model: my_hook.id_model)`

This is not creating a new hook, however, as it is erroring since the callback_url and id_model aren't being set on the new webhook that gets created

The way I eventually had to go about creating a webhook is like this:

`trello.create(:webhook, "callbackUrl" => my_hook.url, "idModel" => my_hook.id_model)`

This could potentially be solved by calling `create` from the `client.save` class, though this may also be by design which is why I am submitting an issue rather than a pull request

**Comment by joneslee85** [comment]
@Haziba thanks for the report, so is it because of symbol hash params? I am trying to grasp the context but I could not understand what you were running into.

**Comment by ownadi** [comment]
I think https://github.com/jeremytregunna/ruby-trello/pull/216 fixes it.
