### ISSUE TITLE
TInternet should bubble up some exceptions

### ISSUE THREAD

**Issue by dobbymoodge** [jeremytregunna/ruby-trello#193]
https://github.com/jeremytregunna/ruby-trello/blob/master/lib/trello/net.rb#L22

If the request fails due to a timeout, the `RestClient::RequestTimeout` exception should be handled by the caller, right? Maybe this should only return a `Response` if `!e.http_code.nil?`

**Comment by joneslee85** [comment]
@dobbymoodge what about returning `408 Request Timeout` response instead?

**Comment by dobbymoodge** [comment]
@joneslee85 That would be misleading - that response is sent by a server when it has accepted a connection, but the client has sent no request, or only a partial request, within some timeout threshold. The request may have failed because of a socket timeout.

Unfortunately, older versions of rest-client bundle both cases under the same `RequestTimeout` exception, though this has been addressed in more recent versions: https://github.com/rest-client/rest-client/issues/337

ruby-trello should raise appropriately distinct exceptions for each of the possible failure cases, where possible. I understand why `RestClient::Exception` is being interpreted as a `Response` struct here, but it really shouldn't be doing that for cases where there is no `http_code` or `http_body` in the `Exception`. On the other hand, if the exception were just passed up here unconditionally, downstream code could take advantage of whatever improvements rest-client makes to its exception code in the future.

**Comment by joneslee85** [comment]
@dobbymoodge 👍 would you be able to send us a PR? TIA

**Comment by dobbymoodge** [comment]
I've got a working patch, just need to update the appropriate test(s)
