### ISSUE TITLE
How i get member details 

### ISSUE THREAD

**Issue by pvin** [jeremytregunna/ruby-trello#200]
```
@client_alice = Trello::Client.new(
  :consumer_key => YOUR_CONSUMER_KEY,
  :consumer_secret => YOUR_CONSUMER_SECRET,
  :oauth_token => "Alice's access token",
  :oauth_token_secret => "Alice's access secret"
)
```
After this how to get member details /  list of boards from members from @client_alice??
Any help here?

**Comment by joneslee85** [comment]
Please ask for help on chat room or put it on StackOverflow instead. The issue here is only for bug reporting and feature discussion.
