### ISSUE TITLE
Ability to mark checklist items complete?

### ISSUE THREAD

**Issue by mockdeep** [jeremytregunna/ruby-trello#203]
I'm trying to write a tool to mark checklist items as complete. Not sure, but it doesn't seem to be possible with this gem. Am I missing something?

**Comment by mockdeep** [comment]
I got it to work with a little monkey patch in my application:

```ruby
module Trello
  class Card < BasicData

    def update_check_item_state(check_item, checklist:, state:)
      unless %w(complete incomplete).include?(state)
        raise "invalid state #{state}"
      end

      client.put(
        "/cards/#{id}" \
        "/checklist/#{checklist.id}" \
        "/checkItem/#{check_item.id}/state",
        value: state,
      )
    end

  end
end
```

**Comment by joneslee85** [comment]
Thanks for reporting with us. As far as I know there is no method in Card to check an item. You could access the item from items attribute and set its state. I think having adding check/uncheck method in Card is a good idea. Would you be able tn submit a PR?

**Comment by mockdeep** [comment]
@joneslee85 sure, I can come up with something. Does the snippet above look reasonable? Wondering how hard it would be to get the card and checklist ids down to the item so that it can update itself directly instead of having to pass both the checklist and item into the card method.

**Comment by joneslee85** [comment]
@mockdeep I think it should be documented and tests are needed too. 

There is `source_card_id` and `source_card_properties` in `Card` that you could use to identify checklists and card. Please see https://github.com/jeremytregunna/ruby-trello/blob/master/lib/trello/card.rb#L108-L112

**Comment by joneslee85** [comment]
@mockdeep ping :D

**Comment by mockdeep** [comment]
@joneslee85 pull requested: https://github.com/jeremytregunna/ruby-trello/pull/207.
