### ISSUE TITLE
Rate Limiting to prevent Trello errors?

### ISSUE THREAD

**Issue by mockdeep** [jeremytregunna/ruby-trello#204]
I saw [this issue](https://github.com/jeremytregunna/ruby-trello/issues/178), but had a slightly different suggestion to handle Trello rate limiting. It would be great if the client automatically accounted for [Trello API rate limits](http://help.trello.com/article/838-api-rate-limits) and simply delayed requests as necessary to prevent errors. I use threading to speed up my scripts, but then [I'll put in some `sleep`s](https://github.com/mockdeep/scripts/blob/master/trello.rb#L59) to prevent hitting the rate limiting.

**Comment by joneslee85** [comment]
@mockdeep I don't think `sleep` is the solution because there is no way you could guarantee the delay helps hitting the API within the threshold, just imagine you have huge number of API calls here. 

I think it should be handled case by case by the user app.

**Comment by mockdeep** [comment]
@joneslee85 sorry, I didn't mean to suggest that there should be an arbitrary `sleep`, more just that that's what worked for me in that case. Here I could see doing something a little more sophisticated to keep track of how many requests have been made within a timeframe. Something like:

```ruby
module Trello
  class Client
    REQUEST_MUTEX = Mutex.new
    WINDOW_SIZE = 10000 # 10 seconds
    MAX_REQUESTS_PER_WINDOW = 100

    class << self
      attr_accessor :window_start, :window_request_count
    end
    ...
    def invoke_verb(name, uri, body = nil)
      REQUEST_MUTEX.synchronize do
        self.class.window_start ||= Time.now
        self.class.window_request_count ||= 0
        if self.class.window_request_count > MAX_REQUESTS_PER_WINDOW && Time.now - self.class.window_start < WINDOW_SIZE
          sleep(WINDOW_SIZE - (Time.now - self.class.window_size))
          self.class.window_start = Time.now
          self.class.window_request_count = 0
        end
        # probably more logic to keep track...
        self.class.window_request_count += 1
      end
      # other invoke stuff
    end
  end
end
```

**Comment by mockdeep** [comment]
I could see making this sort of functionality part of an external gem, though. There's an old [throttling](https://github.com/kpumuk/throttling) gem that does something similar. Maybe I'll try to build something, since I've run into this sort of problem a few times.

**Comment by joneslee85** [comment]
@mockdeep IMHO I want to keep this gem as simple and as close to the supported API that Trello offer. Feature like this tends to be varied case by case. I 👍 if it is handled by a separate gem. I am happy to feature the link to the gem in README should users look for one.

**Comment by mockdeep** [comment]
Sounds good. I'll work on something someday when I'm trying to put off doing something else.

**Comment by psy-q** [comment]
@mockdeep Have you had any success hacking deeper into this? I'm hitting the rate limit a lot as well and will solve it on the client side with a stupid and primitive thing. But since [Trello's rate limits](https://help.trello.com/article/838-api-rate-limits) seem to be hardcoded (?), having a solution in a gem that fits everybody would be much better.

**Comment by mockdeep** [comment]
@psy-q I've generally resolved this with `sleep` and `retry` logic. Here's a simple `Retryer` class with exponential backoff you could toss in your code:

```rb
class Retryer
  def initialize
    @retry_count = 0
  end

  def call(retry_on:, retry_times: 5)
    yield
  rescue StandardError => ex
    raise ex if @retry_count > retry_times || !accepted_error?(ex.class, retry_on)

    @retry_count += 1
    sleep 0.1 * 2**@retry_count
    retry
  end

  def accepted_error?(klass, retry_on)
    retry_on.is_a?(Enumerable) ? retry_on.include?(klass) : retry_on == klass
  end
end
```

Another thing I've done is to manually cache results from Trello to minimize requerying for the same data.

**Comment by psy-q** [comment]
Ah, brilliant, thank you!

**Comment by cblackburn-ajla** [comment]
Not sure when Trello started sending rate-limit stats back in the headers for responses but wouldn't this make it super easy to manage and stay within rate limits? https://developers.trello.com/docs/rate-limits . I'll work on a PR to do use these headers for myself. Hopefully it will be useful to others.
