### ISSUE TITLE
Requires ruby 2.2.2?

### ISSUE THREAD

**Issue by wkoffel** [jeremytregunna/ruby-trello#214]
When trying to install, I get

```
activesupport-5.0.0.1 requires ruby version >= 2.2.2, which is incompatible with the current version, ruby 2.1.7p400
```

But the README says that the gem works on Ruby 2.1.0 and higher.

Is there a new dependency or a version not locked down here that should be?  Or is this library now 2.2.2+ only?

**Comment by joneslee85** [comment]
The lib is >= 2.1.0 as in https://github.com/jeremytregunna/ruby-trello/blob/master/ruby-trello.gemspec#L21

And we do not rely directly on `activesupport`

How do you produce that error?

**Comment by wkoffel** [comment]
So I couldn't figure it out either.  However, I had a few other strange behaviors related to sierra upgrade (I believe), and once I blew away by .rbenv directory entirely, these errors went away.  At this point, I don't believe there's anything broken about the gem (save for a rogue gremlin we're unlikely to track down), so I'll close this.
