### ISSUE TITLE
Drop 1.9 support?

### ISSUE THREAD

**Issue by jeremytregunna** [jeremytregunna/ruby-trello#217]
Opinions? Currently a problem with addressable 2.5.0 as noted in #216. I'm inclined to drop 1.9 support, anyone out there still using 1.9 and unable to upgrade to 2+?

**Comment by jeremytregunna** [comment]
2 more days left open for this issue and I'll close it and make the change unilaterally if nobody has any objections.

**Comment by acuppy** [comment]
@jeremytregunna Will this be a major or minor version bump?

**Comment by jeremytregunna** [comment]
This would be a major version bump according to semver. Since dropping 1.9 would break anyone still using 1.9. This will be done today.

**Comment by jeremytregunna** [comment]
This has been done.
