### ISSUE TITLE
What is purpose of each keys?

### ISSUE THREAD

**Issue by cohki0305** [jeremytregunna/ruby-trello#223]
Hello 

In reading [README](https://github.com/jeremytregunna/ruby-trello), I confused purpose of each keys. 
At first, I cannot find what are `TRELLO_CONSUMER_KEY` and `TRELLO_CONSUMER_SECRET` because these keys are not explained on it.

In addition, I thought that the purpose of `TRELLO_DEVELOPER_PUBLIC_KEY` is similar to `TRELLO_CONSUMER_KEY`.
I did not get difference between `TRELLO_OAUTH_TOKEN` and `TRELLO_CONSUMER_SECRET`.

Please tell me each keys purpose.

**Comment by iburton** [comment]
I assume you got this figured out by now, but you can read about them here: [Trello API Introduction](https://developers.trello.com/get-started/intro#authentication) or in the [README](https://github.com/jeremytregunna/ruby-trello/blob/master/README.md) page of this project in the Configuration section.

**Comment by vasilakisfil** [comment]
@iburton sorry but the links you provided don't help. The documenttion is missing crucial information regarding where to find the keys and what goes where.

**Comment by codyolsen** [comment]
@vasilakisfil I've added a link to the docs to direct to trello's grant page for more clarity in commit https://github.com/jeremytregunna/ruby-trello/commit/57c6302de9f2f123fa3fc054f42b2cfd3f8e78c4 As for the different tokens, they are simply different methods of authenticating to the api. You don't need all of them, but rather one set for each authentication method. You simply pick one method for your needs and BOOM! You are authenticated!

 If you'd like to know more about the purpose for trello's API tokens [check out this stackoverflow answer](https://stackoverflow.com/questions/1592534/what-is-token-based-authentication). I think it does a good job of explaining the concept of token based authentication.
