### ISSUE TITLE
Breaking change 1.4.1 -> 1.5.x

### ISSUE THREAD

**Issue by hakunin** [jeremytregunna/ruby-trello#225]
there seems to be a breaking change in trello gem going from 1.4 -> 1.5

1.4: card.card_labels -> array of objects
1.5:  card.card_labels -> array of ids

to fix, I am using the `labels` method instead:

1.5: card.labels -> array of objects

**Comment by joneslee85** [comment]
@hakunin would you be able to point out the commit that introduced this breaking change? TIA

**Comment by joneslee85** [comment]
Ping @hakunin

**Comment by hakunin** [comment]
Hey, we're not using the gem anymore. I noticed it when test started to fail upon update and then I learned we're dropping it.

**Comment by joneslee85** [comment]
@hakunin the `card_labels` is supposed to return the `idLabels` as you could see in the [spec](https://github.com/jeremytregunna/ruby-trello/blob/master/spec/card_spec.rb#L61).

I believe that in version 1.4, the `card_labels` was mistaken with the `labels` (which is totally different from each other)
