### ISSUE TITLE
Due dates are not set for created cards

### ISSUE THREAD

**Issue by boardfish** [jeremytregunna/ruby-trello#238]
I use the following in my Rails 5 app:

```ruby
      Trello::Card.create(
        name: @todo.title,
        desc: @todo.description,
        due: @todo.due.to_date,
        pos: 'top',
        list_id: '----'
      )
```

All fields work except for due. I've checked on the serverside that the controller receives the due value in the correct format (originally it was receiving as a TimeWithZone, but to_date puts it in Date format as the method requires). Cards are created at the top of the given list with the correct name and description, but they do not have a due date.

**Comment by radubogdan** [comment]
Did you fix the problem @boardfish? I can see there is [a spec covering this case](https://github.com/jeremytregunna/ruby-trello/blob/64a44ffe415296a64c660623e7dc8c375e70ab6d/spec/card_spec.rb#L76) which means it should work.

What happens if you try and [update it](https://github.com/jeremytregunna/ruby-trello/blob/64a44ffe415296a64c660623e7dc8c375e70ab6d/lib/trello/card.rb#L171)?

**Comment by boardfish** [comment]
Sorry for the delay on this - I'm getting a fresh problem with it now that I'm finally able to work on org-mode again.

**Comment by spleenteo** [comment]
Hi,
I've a similar problem

```
d = DateTime.parse("2018-03-06 19:15:59")

options = {
  name: 'Card title,
  desc: "desc",
  due: d
}
c = Trello::Card.create(options)
```
I tryed with DateTime object and string, and the output for the date is always the same: nil

```
#<Trello::Card:0x00007f9b78385340
 @attributes=
  {:id=>"5a9e9896f44f48e1fbd274ec",
   :short_id=>8,
   :due=>nil,
   :due_complete=>false,
   :closed=>false,
```
The card on Trello is created with no due date.

I'm getting lost! :)
Can you help me please? Thanks

**Comment by alex-benoit** [comment]
Just encountered the bug too 👍

**Comment by jeremylinlin** [comment]
Still no solution to this problem yet?

**Comment by baldrailers** [comment]
That field is looking for `ISO8601` to pass it properly, you'll have to:
```
{
due: Date.parse('05/09/2018').to_time.iso8601
....
}
```
