### ISSUE TITLE
Not compatible with Active Model 5.2

### ISSUE THREAD

**Issue by gretzki** [jeremytregunna/ruby-trello#246]
Using ruby-trello 2.0.1 and latest activemodel gem (5.2) fails with the following error:

> activemodel-5.2.0.beta2/lib/active_model/attribute_mutation_tracker.rb:45:in `changed?': undefined method `changed?' for nil:NilClass (NoMethodError)
> 	from activemodel-5.2.0.beta2/lib/active_model/dirty.rb:288:in `changes_include?'
> 	from activemodel-5.2.0.beta2/lib/active_model/dirty.rb:172:in `attribute_changed?'
> 	from activemodel-5.2.0.beta2/lib/active_model/dirty.rb:310:in `attribute_will_change!'
> 	from activemodel-5.2.0.beta2/lib/active_model/attribute_methods.rb:382:in `pos_will_change!'
> 	from ruby-trello-2.0.1/lib/trello/basic_data.rb:60:in `block (3 levels) in register_attributes'

Locking ActiveModel gem to 4.2.10 solves this issue

**Comment by mjankowski** [comment]
I started to dig on this and hit the point where my knowledge of both `ruby-trello` and `ActiveModel` came up short ... this looks connected to how the dirty attributes api/implementation changed in 5.2.

**Comment by wokenqingtian** [comment]
I have faced this issue recently and done a fix. [PR-261](https://github.com/jeremytregunna/ruby-trello/pull/261)

**Comment by dougcouvillion** [comment]
I'm having this issue too.  Any idea when @wokenqingtian 's PR might get merged?

**Comment by srgoldman** [comment]
Verified the PR fixes the issue for me as well. Can we please get it merged? @jeremytregunna ?

**Comment by jeremytregunna** [comment]
@srgoldman yes, apologies for not having payed a ton of attention to this.

**Comment by jeremytregunna** [comment]
I've also cut version 2.2.0 and published the gem.

**Comment by srgoldman** [comment]
awesome, thanks!
