### ISSUE TITLE
Travis CI builds cannot complete due to errors.

### ISSUE THREAD

**Issue by kaylaziegler** [jeremytregunna/ruby-trello#252]
### To reproduce:
Issue a PR or add a commit. It appears to be happening with every build now. I'm not sure when it began but it first showed up with my PR: https://github.com/jeremytregunna/ruby-trello/pull/250. Then the same exact error happened with the subsequent PR: https://github.com/jeremytregunna/ruby-trello/pull/251.

### Error:
See [Build #582](https://travis-ci.org/jeremytregunna/ruby-trello/builds/382884742) and [Build #583](https://travis-ci.org/jeremytregunna/ruby-trello/builds/383916141) in Travis. The failing jobs are the same 2, the ones that use `jruby-head`. The failed command is `bundle install`, this is the output:

```
$ bundle install --jobs=3 --retry=3
[!] There was an error parsing `Gemfile`: Unknown special char: Y. Bundler cannot continue.
```
That's all the available info I have. Neither pull request modified the Gemfile so it doesn't seem related to the actual changes made. There must be a log or something somewhere that the admins have access to that could tell more but as it stands I'm not sure how to fix this.

**Comment by codyolsen** [comment]
@kaylaziegler Thanks for the report. After searching the latest build errors I discovered that travis did some updates about 12 days ago. I reran the latest build and it passed.
