### ISSUE TITLE
Create a complete board from a .json

### ISSUE THREAD

**Issue by matheussbernardo** [jeremytregunna/ruby-trello#253]
Hello,

I have a JSON file that contains info of a board with cards and lists, is it possible to use the gem/api to create a new board from this file with only one call to the api?

the file is https://gist.github.com/matheussbernardo/57edb503de286da9cf1e87221fcf615b

**Comment by codyolsen** [comment]
@matheussbernardo I don't believe so. You'd have to parse the JSON tree and create separate api calls for creating each element -> [board, list, card, etc]

There might be a better way here: [Trello Data Importing](https://help.trello.com/article/751-importing-data-into-trello)
