### ISSUE TITLE
Trello::Error: invalid token using Trello::Client

### ISSUE THREAD

**Issue by AnatolySt** [jeremytregunna/ruby-trello#264]
I am using Ruby on Rails 5.2 and gems: ruby-trello, devise, omniauth-trello.
Sorry for my English.

I want to make authorized requests on behalf of Trello user same as shows here: https://github.com/jeremytregunna/ruby-trello#multiple-users

Example from docs:

    @client_bob = Trello::Client.new(
      :consumer_key => YOUR_CONSUMER_KEY,
      :consumer_secret => YOUR_CONSUMER_SECRET,
      :oauth_token => "Bob's access token",
      :oauth_token_secret => "Bob's access secret"
    )

Trello configured by "basic authorization": https://github.com/jeremytregunna/ruby-trello#basic-authorization

My steps:

 1. User (Bob) sign in with Trello (omniauth) and get his own oauth_secret and oauth_token
 2. In my app I create a Trello::Client for Bob using:
       - his own oauth data (:oauth_token, :oauth_token_secret)
       - I got consumer_key from here: https://trello.com/app-key (in the top of page, first block with key field)
       - consumer_secret was taken from https://trello.com/app-key too, but from the bottom of page, last block with key secret

After this, I'm trying to get any data from Bob's trello account (boards, lists, tasks etc.) but always getting 500 error (invalid token).

Could you explain what I'm doing wrong?
Thank you in advance.

Note: I have already asked at stackoverflow. No one answer

**Comment by Christm4s** [comment]
Click this link (https://trello.com/app-key) to find your app key. In the paragraph right below the app key, there's a hyperlink to generate your token. Click authorize on the next page after you click the hyperlink to get your token.
