### ISSUE TITLE
Unable to update card

### ISSUE THREAD

**Issue by cavemangraham** [jeremytregunna/ruby-trello#272]
I have the following code:

```
card = Trello::Card.create(name: card_name, list_id: list_id, desc: description)

card_update = Trello::Card.find(@order.trello_card_id)

updated = card_update.update_fields(name: "123", desc: description).update!

p updated
```
The card is created with no problems with the correct attributes but I am unable to make any updates to it after that.

I have tried using .save as well as .update! and my update actions comes back with a "<RestClient::Response 200 "{\"id\":\"5dfb...">" response but the card itself on Trello does not change.

I have updated the ruby-trello gem to 2.2.0 and am on Rails 5.2.4.1 and ruby 2.6.3p62

Is there anything I can do to get it to update properly? I feel like I am making a simple mistake but I can't figure out where. Thanks in advance!

**Comment by wokenqingtian** [comment]
This issue has been fixed in https://github.com/jeremytregunna/ruby-trello/pull/273
