### ISSUE TITLE
`to_a` and `to_ary` do not return Arrays

### ISSUE THREAD

**Issue by cedrics** [jeremytregunna/ruby-trello#274]
I wanted to do something like `board.lists.flat_map(&:cards)`, however this will raise an exception:

```
TypeError (can't convert Trello::AssociationProxy to Array (Trello::AssociationProxy#to_ary gives Trello::MultiAssociation))
```

This is due to `to_a` being defined in a wrong manner:

```ruby
board.lists.class
=> Array
board.lists.to_a.class
=> Trello::MultiAssociation
board.lists.to_a.class.ancestors.include?(Array)
=> false
```

This is the same issue as https://github.com/jeremytregunna/ruby-trello/issues/160.

**Comment by wokenqingtian** [comment]
I have fixed it.

**Comment by cedrics** [comment]
Thank you @wokenqingtian ❤️
