### ISSUE TITLE
Permission bits for '/home/user/.netrc' should be 0600, but are 644

### ISSUE THREAD

**Issue by rodrigo-puente** [jeremytregunna/ruby-trello#280]
I'm trying to get the members of an organization:

```
org = Trello::Organization.find('awesomeinternet')
org.members
```

But I get
```
Permission bits for '/home/user/.netrc' should be 0600, but are 644
```

Should I just `chmod` the file or is something weird happening here?

**Comment by wokenqingtian** [comment]
Trello gem use [rest-client](https://github.com/rest-client/rest-client) to make the request. And this seems is [an issue](https://github.com/rest-client/rest-client/issues/663) belongs to rest-client.

As my point of view, you can just do what the error message says - `chmod` the file to 0600
