### ISSUE TITLE
Keep support JRuby and Rubinius or not?

### ISSUE THREAD

**Issue by wokenqingtian** [jeremytregunna/ruby-trello#286]
Our CI doesn't test for JRuby and Rubinius. But I found these codes in our project:

```ruby
# spec/spec_helper
unless defined? Rubinius
  require 'simplecov'
  SimpleCov.start
end
```

```ruby
# Gemfile
gem 'jruby-openssl', :platforms => :jruby
```

Should we keep supporting them? If the answer is yes, it seems we need to add CI tests for them. If the answer is no, I may prepare to remove them.

**Comment by runlevel5** [comment]
I reckon we should support JRuby as it is still being worked on by the community.

**Comment by jeremytregunna** [comment]
Yes we should keep JRuby support, I'll continue this in #287
