### ISSUE TITLE
Pushing updates to rubygems by others

### ISSUE THREAD

**Issue by jeremytregunna** [jeremytregunna/ruby-trello#292]
Right now, I'm the only one who can push changes to the gem. I'd like to allow some contributors to this repository to be able to push changes to push a release out. Anyone have any thoughts on a good secure way to accommodate this? My main thought is GitHub Actions. I feel like I am not available frequent enough to be the only one who can push bug fixes out to rubygems.

**Comment by wokenqingtian** [comment]
I would like to do some research on this next month

**Comment by wokenqingtian** [comment]
After some research, I found the old release way maybe is still a better way to release Ruby gem for an opensource project.

### We cannot do permission management on a specific user on Github

All collaborators can:

- create and edit releases
- Publish packages

### Seems not much popular ruby repos use it for release

I didn't find any popular ruby gems which are using GitHub Action for release. Even GitHub itself is not using GitHub action to do automate releases. 

### GitHub Action can't work with the RubyGems OTP

[I asked a question under github/view_component.](https://github.com/github/view_component/discussions/422) about the Github Action. They say GitHub action can't work with the OTP, so they are not using it.

### Summary

So it seems that we have two options:

- If we currently not using OTP, and want to allow all collaborators have the permission to do release works then it's good enough to [deploy with GitHub actions](https://github.com/actions/starter-workflows/blob/e11672e5a9026a98ce6235af089d3112ec93dbd5/ci/gem-push.yml).
- If we consider the security concern as the most important thing, we maybe have to go with the old way - [gem owner command](https://guides.rubygems.org/command-reference/#gem-owner). Add a few collaborators as the gem owners like runlevel5 and me.

References:
* [Permission levels for a user account repository](https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/permission-levels-for-a-user-account-repository)
* [Permission levels for an organization](https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/permission-levels-for-an-organization)

**Comment by jeremytregunna** [comment]
@wokenqingtian Thanks for this, I think the best way to approach this is to see if you and @runlevel5 are both interested in being able to push to rubygems, ruby-trello updates. You are the two people I had in mind. I'd like both your feedback, and the owner approach is what I'll probably settle on.

**Comment by runlevel5** [comment]
@jeremytregunna I am happy to help

**Comment by jeremytregunna** [comment]
@runlevel5 Alright, shoot me an email jeremy@tregunna.ca with your email

**Comment by wokenqingtian** [comment]
@jeremytregunna I would like to do this with @runlevel5. Also, emailed you.

**Comment by jeremytregunna** [comment]
@wokenqingtian Thanks, just waiting on @runlevel5's email to add as well, but you were just added.

**Comment by jeremytregunna** [comment]
I'm going to close this issue for now, please @runlevel5 let me know via email the address you use on rubygems, and I'll add you. No sense in keeping this issue open right now though.
