### ISSUE TITLE
Due dates are not set for created cards

### ISSUE THREAD

**Issue by ShunnMatsumura** [jeremytregunna/ruby-trello#295]
I ran it with the following script in reference to [#238](https://github.com/jeremytregunna/ruby-trello/issues/238), but it gives me invalid error. 
Someone please help me.

The time zone is 'Asia/Tokyo' in my dev env, so I converted it to UTC and then posted it, but I got an error.

```
options = {
...
  due: Time.current.in_time_zone('UTC').to_time.iso8601,
...
}

Trello::Card.create(options)

pry(main)> Trello::Card.create(options)
E, [2020-09-02T06:17:39.820368 #1] ERROR -- : [400 POST https://api.trello.com/1/cards]: {"message":"invalid date","error":"ERROR"}
Trello::Error: {"message":"invalid date","error":"ERROR"}
from /bundle-alpine/gems/ruby-trello-2.3.1/lib/trello/client.rb:99:in `invoke_verb'
```

I've also tried the following with no success.

```
due: Date.current.in_time_zone('UTC').to_time.iso8601
due: Date.parse('2020-09-03 04:53:00 UTC').iso8601
due: Date.parse('2020-09-03 04:53:00 UTC')
```

please help me.

**Comment by wokenqingtian** [comment]
I just try this on my side but failed to reproduce it. It works fine on my side. It seems that I need more details about your local development environment like the Ruby version, the Rails version ...

Maybe you can also try the Trello official time format `time.strftime('%FT%T.%LZ')` which we will use it in the next major version.
