### ISSUE TITLE
Attachment creation is broken when using faraday as an http client

### ISSUE THREAD

**Issue by alexeyramazanov** [jeremytregunna/ruby-trello#311]
```ruby
Trello::Card.find('id').add_attachment(File.open('file.pdf'), 'file.pdf')
# => DEBUG -- request: {:file=>#<File:file.pdf>, :name=>"file.pdf"}
# => {"message":"Must provide either url or file","error":"VALIDATOR_INVALID_VALUE"} (Trello::Error)
```
doesn't work because faraday doesn't automatically convert `File` objects in body into multipart/form-data.

Proper usage should include initialization of `Faraday::Multipart::FilePart` object and [faraday-multipart](https://github.com/lostisland/faraday-multipart) should be added to the faraday connection object.

**Comment by hoppergee** [comment]
Sorry for the late response. I'll take a look this week.

**Comment by hoppergee** [comment]
@alexeyramazanov I just released [a new minor version](https://github.com/jeremytregunna/ruby-trello/releases/tag/v4.1.0) to fix this issue.
