### ISSUE TITLE
Values returned by optional parameters ignored

### ISSUE THREAD

**Issue by mriddle** [jeremytregunna/ruby-trello#80]
The trello gem has the ability to provide additional parameters `Trello::Board.find(board_id, :members => "normal")` yet because the way the attributes are set the retrieved values are dropped. 

https://github.com/jeremytregunna/ruby-trello/blob/master/lib/trello/board.rb#L54-62

In this case I was expecting the members on the board to be populated, but instead when calling board.members I make a separate request.

Is this by design? If we had something like it would be less brittle when Trello changes their API. 

```ruby
#lib/board.rb
def update_fields(fields)
  attributes = fields.symbolize_keys.except(:desc, :idOrganization, :prefs)
  attributes[:description]     = fields['desc']            if fields['desc']
  attributes[:organization_id] = fields['idOrganization']  if fields['idOrganization']
  attributes[:prefs]           = fields['prefs'] || {}
  self
end
```
However I noticed that you also register the attributes, causing the change above to break stuff. Why is that?

Going down the path of making a separate request but I was curious.

**Comment by joneslee85** [comment]
It's been quite a long time since the last reply and no action were made. I close the ticket for now, feel free to re-open it.
