### ISSUE TITLE
I couldn't figure out how to add member to a board

### ISSUE THREAD

**Issue by fredxinfan** [jeremytregunna/ruby-trello#96]
I was trying to use this gem add members into a board and then assign them to the cards. The code is as the following:
board = Trello::Board.find board_id
member = Trello::Member.find member_id
board.members << member
It returns an error says undefined method `concat' for #<Trello::MultiAssociation:0x007fdafc02b348>
I could add member to the board by using client.put("/boards/#{board.id}/members/#{member.id}"), but just wondering if there is a better way already implemented some where in the gem that I haven't noticed?

**Comment by ssaunier** [comment]
Facing the same exact problem. Should we add an `add_member` method to a board? Or is there a generic way to fix the `<<` approach?
