### ISSUE TITLE
Getting archived cards

### ISSUE THREAD

**Issue by NenadP** [jeremytregunna/ruby-trello#97]
It seems when I pull trello cards from the board lists, it does not pull archived cards too ? Is there a way to get archived ones too ?

thanks

**Comment by Anti-Fun** [comment]
Hey guys,

[As per the following lines of code] (https://github.com/jeremytregunna/ruby-trello/blob/master/lib/trello/board.rb#L78-83)

You can specify a hash table with filter, here is a quick example:

```ruby
Trello::Board.all.each do |board|
  board.cards( { filter: :all } ).each do |card|
    puts card
  end
end
```

IMO it makes sense to only retrieve active cards by default.
