### ISSUE TITLE
some methods missing proper API documentation

### ISSUE THREAD

**Issue by aspiers** [jeremytregunna/ruby-trello#99]
Some of [the attributes registered in `Trello::Member`](https://github.com/jeremytregunna/ruby-trello/blob/836b867a95bd987a683fc4eb68e84d7159a634d0/lib/trello/member.rb#L4), such as `#initials`, `#avatar_id` etc., do not appear in the API docs.  The only way to discover some of them is to read the source.

**Comment by larryprice** [comment]
Looks like they're documented now: http://www.rubydoc.info/gems/ruby-trello/Trello/Member. Can you see them now?

**Comment by aspiers** [comment]
Thanks - I can now see them, which is an improvement, but they're still not documented.  Attributes such as `bio` and `full_name` are maybe too obvious to need documentation, but `avatar_id` is a bit less obvious (i.e. how do you use it once you have it?)

**Comment by joneslee85** [comment]
It's been quite a long time since the last reply and no action were made. I close the ticket for now, feel free to re-open it.

**Comment by fiedl** [comment]
For others landing here via google: In order to get the avatar image url, use:

```ruby
Trello::Member.find(...).avatar_url
```
